[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200

remappings = [
    "forge-std/=lib/forge-std/src/",
    "v4-core/=lib/v4-periphery/lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@openzeppelin/=lib/v4-periphery/lib/v4-core/lib/openzeppelin-contracts/",
]

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"
base_sepolia = "https://sepolia.base.org"

[etherscan]
arc_testnet = { key = "", url = "https://testnet.arcscan.app/api" }
